#!/bin/sh
#
# shockd-mgrast      init file for starting up the shockd server for the $tenant 
#
# chkconfig:   - 91 10
# description: Starts and stops the shock daemon that handles all \
#              mgrast database requests.

tenant="mgrast"           # TENANT

. /etc/rc.d/init.d/shockd-functions

## END OF LINE ##
